spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roadmap_project
    username: group37
    password: password
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  sql:
    init:
      mode: always

logging.level.org:
  hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  springframework:
    jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE
    security: DEBUG